name: PIFu
channels:
  - defaults
  - conda-forge
  - pytorch
  - nvidia
dependencies:
  - python=3.11
  - pytorch=2.1.2=*cuda11.8* # remove cuda tag for macOS
  - torchvision
  - torchaudio
  - ffmpeg
  - imageio>=2.34.0
  - libjpeg-turbo
  - libnvjpeg-dev # exclude it for macOS
  - numpy
  - ocl-icd-system # exclude it for macOS
  - opencv
  - openexr
  - pillow
  - rtree
  - scikit-image
  - shapely
  - tqdm
  - xxhash
  - pip
  - pip:
    - pyembree
    - pysdf
    - open3d
    - pyopengl
variables:
  PYTORCH_ENABLE_MPS_FALLBACK: '1'