name: PIFu
channels:
  - defaults
  - conda-forge
  - pytorch
  - nvidia
dependencies:
  - python=3.11
  - pytorch=2.0.1=*cuda11.7*
  - torchvision
  - torchaudio
  - ffmpeg
  - imageio>=2.34.0
  - libjpeg-turbo
  - numpy
  - opencv
  - openexr
  - pillow
  - rtree
  - scikit-image
  - shapely
  - tqdm
  - xxhash
  - pip
  - pip:
    - pyembree
    - pysdf
    - open3d
    - pyopengl
variables:
  PYTORCH_ENABLE_MPS_FALLBACK: '1'