name: PIFu
channels:
  - defaults
  - conda-forge
  - pytorch
  - nvidia
dependencies:
  - python=3.8
  - pytorch=*=*cuda11.7*
  - torchvision=*=*cu117*
  - torchaudio=*=*cu117*
  - ffmpeg
  - freeglut
  - imageio>=2.34.0
  - numpy<=1.23.1
  - opencv
  - openexr
  - pillow
  - pyopengl
  - rtree
  - scikit-image
  - shapely
  - tqdm
  - xxhash
  - pip
  - pip:
    - pyembree
    - pysdf
    - open3d