name: PIFu
channels:
  - defaults
  - conda-forge
  - pytorch
  - nvidia
dependencies:
  - python=3.10
  - pytorch=*=*cuda11.8*
  - torchvision=*=*cu118*
  - torchaudio=*=*cu118*
  - ffmpeg
  - freeglut
  - numpy<=1.23.1
  - opencv
  - openexr
  - pillow
  - pyembree
  - pyopengl
  - rtree
  - scikit-image
  - shapely
  - tqdm
  - trimesh
  - xxhash