name: PIFu
channels:
  - defaults
  - conda-forge
  - pytorch
  - nvidia
dependencies:
  - python=3.8
  - pytorch=2.0.1
  - torchvision
  - torchaudio
  - ffmpeg
  - imageio=2.34.0
  - numpy<=1.23.1
  - opencv
  - openexr
  - pillow
  - rtree
  - scikit-image
  - shapely
  - tqdm
  - xxhash
  - pip
  - pip:
    - pyembree
    - pysdf
    - open3d
    - pyopengl
variables:
  PYTORCH_ENABLE_MPS_FALLBACK: '1'